### ISSUE TITLE
[WIP] - Improved UX for the Online page

### ISSUE THREAD

**Issue by jsheunis** [jsheunis/online-brain#3]
General feature requests that would improve the UX:

- [x] Add page heading. E.g. the settings page says "Basic settings" at the top. This page could say "Real-time operation" for now.
- [x] Swop next and previous button positions
- [x] Display "Volume number: Template" for the first image before real-time visualisation is 
 active.
- [x] add crosshairs and position to the template image sprite (similar to display settings of real-time sprites), they are not displaying currently
- [x] Is it possible to trigger the `file_copy_script.py` from the app on this page. Some thing like a "Start real-time simulation" button.

**Comment by drgs** [comment]
Can you add more details regarding the "Add page heading" task?
